### PR TITLE
Unstructure before mapping in `order_proxy()`

### LINKED ISSUE #1298: vec_order(<tibble>) -> using deprecated names<-.tbl_df
originally from https://github.com/tidyverse/dplyr/issues/5622

``` r
library(vctrs)
library(tibble)
#> 
#> Attaching package: 'tibble'
#> The following object is masked from 'package:vctrs':
#> 
#>     data_frame
Sys.unsetenv("RSTUDIO")
options(lifecycle_verbosity = "error")

vec_order(tibble(x = c(0, 1, 1, 1), y = c(1, 1, 0, 0)))
#> Error: The `value` argument of ``names<-`()` can't be NULL as of tibble 3.0.0.
#> `names` must not be `NULL`.
```

<sup>Created on 2020-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #1298 

Avoids any calls to `names(x) <- NULL` by unstructuring rather than unnaming.

### CODE REVIEW

File: tests/testthat/test-order.R [hunk 1]
```diff
@@ -68,3 +68,14 @@ test_that("classed proxies do not affect performance (tidyverse/dplyr#5423)", {
   x <- glue::glue("{1:10000}")
   expect_time_lt(vec_order(x), 0.2)
 })
+
+test_that("can order tibbles without names warning (#1298)", {
+  skip_if_not_installed("tibble", minimum_version = "3.0.0")
+  skip_if_not_installed("withr")
```
Comment (lionel-) [inline tests/testthat/test-order.R:74]: Can you create a custom `names()` method for this test instead of using tibble please?

**Review by lionel- — APPROVED** [review]
