### PR TITLE
Call out complex as an incomparable type

### LINKED ISSUE #1655: Internal error: comparing to complex
``` r
vctrs::vec_compare(1,1i)
#> Error in `vctrs::vec_compare()`:
#> ! Unsupported vctrs type `complex`.
#> ℹ In file 'type-info.c' at line 177.
#> ℹ This is an internal error in the vctrs package, please report it to the package authors.

#> Backtrace:
#>     ▆
#>  1. ├─vctrs::vec_compare(1, 0+1i)
#>  2. └─rlang:::stop_internal_c_lib(...)
#>  3.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)
```

<sup>Created on 2022-09-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #1655 

This at least avoids an internal error.

### CODE REVIEW

File: src/compare.c [hunk 1]
```diff
@@ -50,8 +50,9 @@ r_obj* vec_compare(r_obj* x, r_obj* y, bool na_equal) {
     case VCTRS_TYPE_integer:   COMPARE(int, r_int_cbegin, int_compare_na_equal);
     case VCTRS_TYPE_double:    COMPARE(double, r_dbl_cbegin, dbl_compare_na_equal);
     case VCTRS_TYPE_character: COMPARE(r_obj*, r_chr_cbegin, chr_compare_na_equal);
-    case VCTRS_TYPE_scalar:    r_abort("Can't compare scalars with `vec_compare()`");
-    case VCTRS_TYPE_list:      r_abort("Can't compare lists with `vec_compare()`");
+    case VCTRS_TYPE_complex:   r_abort("Can't compare complexes with `vec_compare()`.");
+    case VCTRS_TYPE_scalar:    r_abort("Can't compare scalars with `vec_compare()`.");
+    case VCTRS_TYPE_list:      r_abort("Can't compare lists with `vec_compare()`.");
```
Comment (lionel-) [inline src/compare.c:55]: I think it's redundant to mention `vec_compare()` here, since it'll be part of the call?

**Review by lionel- — APPROVED** [review]
