### PR TITLE
Use `vec_proxy()` in equality comparisons

### LINKED ISSUE #337: Problem when executing pivot_longer from the tidyr package.
This is an issue which occurred in connection with this issue in the dplyr repo (https://github.com/tidyverse/dplyr/issues/4367) and is about tidyr/vctrs.

I am running into an error in connection with the new function `pivot_longer`, which is the equivalent to the old `gather` function.

I will show two examples, one executed using the `gather` function and one using the `pivot_longer` function.

```{R}
> df_results_samples
   Row Column Sample Sample_split internal_id      ITAC      GM_CSF
1    A      4  167_1          167           1  52.35781          NA
2    B      4  167_1          167           1  54.76764 37331.36022
3    C      4  167_3          167           3  61.58428          NA
4    D      4  167_3          167           3  62.74383 37331.36022
5    E      4  167_5          167           5  53.78760  1202.27184
6    F      4  167_5          167           5  47.13884   594.17293
7    G      4  166_7          166           7 106.32665          NA
8    H      4  166_7          166           7 123.24450          NA
9    A      5  167_2          167           2  93.15707    49.65751
10   B      5  167_2          167           2  89.13810    48.89627
> 
> df_results_samples <- df_results_samples %>%
+   tidyr::gather(data = ., key = "cytokine", value = "concentration", 6:7)
> 
> df_results_samples
   Row Column Sample Sample_split internal_id cytokine concentration
1    A      4  167_1          167           1     ITAC      52.35781
2    B      4  167_1          167           1     ITAC      54.76764
3    C      4  167_3          167           3     ITAC      61.58428
4    D      4  167_3          167           3     ITAC      62.74383
5    E      4  167_5          167           5     ITAC      53.78760
6    F      4  167_5          167           5     ITAC      47.13884
7    G      4  166_7          166           7     ITAC     106.32665
8    H      4  166_7          166           7     ITAC     123.24450
9    A      5  167_2          167           2     ITAC      93.15707
10   B      5  167_2          167           2     ITAC      89.13810
11   A      4  167_1          167           1   GM_CSF            NA
12   B      4  167_1          167           1   GM_CSF   37331.36022
13   C      4  167_3          167           3   GM_CSF            NA
14   D      4  167_3          167           3   GM_CSF   37331.36022
15   E      4  167_5          167           5   GM_CSF    1202.27184
16   F      4  167_5          167           5   GM_CSF     594.17293
17   G      4  166_7          166           7   GM_CSF            NA
18   H      4  166_7          166           7   GM_CSF            NA
19   A      5  167_2          167           2   GM_CSF      49.65751
20   B      5  167_2          167           2   GM_CSF      48.89627
> sessionInfo()
R Under development (unstable) (2019-03-24 r76263)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.2  ggplot2_3.1.1      tidyr_0.8.3        dplyr_0.8.1        readr_1.3.1        BiocManager_1.30.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       rstudioapi_0.10  magrittr_1.5     hms_0.4.2        tidyselect_0.2.5 munsell_0.5.0    colorspace_1.4-1
 [8] R6_2.4.0         rlang_0.3.4.9003 plyr_1.8.4       tools_3.6.0      grid_3.6.0       gtable_0.3.0     withr_2.1.2     
[15] lazyeval_0.2.2   yaml_2.2.0       assertthat_0.2.1 tibble_2.1.1     crayon_1.3.4     purrr_0.3.2      vctrs_0.1.0.9003
[22] zeallot_0.1.0    glue_1.3.1       stringi_1.4.3    compiler_3.6.0   pillar_1.4.0     scales_1.0.0     backports_1.1.4 
[29] pkgconfig_2.0.2
```

Next is an example which failed when switching to the development version of tidyr for using the `pivot_longer` function.

```{R}
> df_results_samples
   Row Column Sample Sample_split internal_id      ITAC      GM_CSF
1    A      4  167_1          167           1  52.35781          NA
2    B      4  167_1          167           1  54.76764 37331.36022
3    C      4  167_3          167           3  61.58428          NA
4    D      4  167_3          167           3  62.74383 37331.36022
5    E      4  167_5          167           5  53.78760  1202.27184
6    F      4  167_5          167           5  47.13884   594.17293
7    G      4  166_7          166           7 106.32665          NA
8    H      4  166_7          166           7 123.24450          NA
9    A      5  167_2          167           2  93.15707    49.65751
10   B      5  167_2          167           2  89.13810    48.89627
> 
> df_results_samples <- df_results_samples %>%
+   tidyr::pivot_longer(data = ., cols = 6:7, names_to = "cytokine", values_to = "concentration")
Error: Unsupported vctrs type `s3` in `equal_scalar()`
> sessionInfo()
R Under development (unstable) (2019-03-24 r76263)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.2  ggplot2_3.1.1      tidyr_0.8.3.9000   dplyr_0.8.1        readr_1.3.1        BiocManager_1.30.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1          rstudioapi_0.10     magrittr_1.5        hms_0.4.2           tidyselect_0.2.5    munsell_0.5.0      
 [7] colorspace_1.4-1    R6_2.4.0            rlang_0.3.4.9003    plyr_1.8.4          tools_3.6.0         grid_3.6.0         
[13] gtable_0.3.0        withr_2.1.2         ellipsis_0.1.0.9000 lazyeval_0.2.2      yaml_2.2.0          assertthat_0.2.1   
[19] tibble_2.1.1        crayon_1.3.4        purrr_0.3.2         vctrs_0.1.0.9003    zeallot_0.1.0       glue_1.3.1         
[25] stringi_1.4.3       compiler_3.6.0      pillar_1.4.0        scales_1.0.0        backports_1.1.4     pkgconfig_2.0.2
```

The `gather` function still works with the development version of tidyr.

Thanks for the help and support!

### PR DESCRIPTION
**Pull request by lionel-**
This might need a little more work, but this should fix #337 and tidyr.

### CODE REVIEW

File: tests/testthat/test-dictionary.R [hunk 1]
```diff
@@ -65,6 +65,9 @@ test_that("also works for data frames", {
   count <- vec_count(df2, sort = "key")
   expect_equal(count$key, df)
   expect_equal(count$count, vec_count(idx)$count)
+
+  exp <- tibble(x = c(1, 1, 2), y = c(1, 2, 3))
+  expect_identical(vec_unique(tibble(x = c(1, 1, 1, 2), y = c(1, 2, 2, 3))), exp)
```
Comment (hadley) [inline tests/testthat/test-dictionary.R]: Might be slight more clear to construct this with `vec_slice(exp, c(1, 1, 2, 3))`?

File: vignettes/s3-vector.Rmd [hunk 2]
```diff
@@ -629,9 +629,7 @@ decimal2(10, c(0, 5, 99))
 
 vctrs provides two "proxy" generics that lets you control how your class determines equality and ordering:
 
-* `vec_proxy_equal()` specifies how to test the elements of your vector for equality. 
-  This proxy underpins `==` and `!=`, but also `unique()`, `anyDuplicated()`, 
-  and `is.na()`.
+* `vec_proxy()` is the main way for an arbitrary class that doesn't inherit from `vctrs_vctr` to be compatible with vctrs. It is used in most vctrs primitives, including equality comparison. This proxy thus underpins `==` and `!=`, `unique()`, `anyDuplicated()`, and `is.na()`.
```
Comment (hadley) [inline vignettes/s3-vector.Rmd]: We need to mention this in the news too — it's technically a major change, although I doubt anyone has depended on it yet.

Comment (hadley) [reply vignettes/s3-vector.Rmd]: I think the fact that you can use this to make an arbitrary class compatible with vctrs isn't relevant (or at least not primary here).

File: vignettes/s3-vector.Rmd [hunk 3]
```diff
@@ -643,18 +641,18 @@ These proxy functions should always return a simple object (typically either a b
...
 x
 
-vec_proxy_equal(x)
+vec_proxy(x)
 
 x == rational(1, 1)
 ```
 
-This makes sense as a default, but isn't correct here because `rational(1, 1)` represents the same number as `rational(2, 2)` so they should be equal. We can fix that by implementation `vec_proxy_equal()` method that by divides `n` and `d` by their greatest common divisor:
+This makes sense as a default, but isn't correct here because `rational(1, 1)` represents the same number as `rational(2, 2)` so they should be equal. We can fix that by implementation `vec_proxy()` method that by divides `n` and `d` by their greatest common divisor:
```
Comment (hadley) [inline vignettes/s3-vector.Rmd]:
```suggestion
This makes sense as a default, but isn't correct here because `rational(1, 1)` represents the same number as `rational(2, 2)` so they should be equal. We can fix that by implementing a `vec_proxy()` method that by divides `n` and `d` by their greatest common divisor:
```

File: R/compare.R [hunk 4]
```diff
@@ -74,7 +71,7 @@ vec_proxy_compare.default <- function(x, relax = FALSE) {
 vec_compare <- function(x, y, na_equal = FALSE, .ptype = NULL) {
   args <- vec_recycle_common(x, y)
   args <- vec_cast_common(!!!args, .to = .ptype)
-  .Call(vctrs_compare, vec_proxy_equal(args[[1]]), vec_proxy_equal(args[[2]]), na_equal)
+  .Call(vctrs_compare, vec_proxy_compare(args[[1]]), vec_proxy_compare(args[[2]]), na_equal)
```
Comment (hadley) [inline R/compare.R]: This was a bug, right? Surely `vec_compare()` always should've used `vec_proxy_compare()`?

File: src/equal.c [hunk 5]
```diff
@@ -19,7 +19,7 @@ int equal_scalar(SEXP x, R_len_t i, SEXP y, R_len_t j, bool na_equal) {
   default: break;
   }
 
-  switch (vec_typeof(x)) {
+  switch (vec_proxy_typeof(x)) {
   case vctrs_type_list: return list_equal_scalar(x, i, y, j, na_equal);
   case vctrs_type_dataframe: return df_equal_scalar(x, i, y, j, na_equal);
```
Comment (hadley) [inline src/equal.c]: Do we also need to think about tibbles here?

File: vignettes/s3-vector.Rmd (hunk 2 above)
Comment (DavisVaughan) [reply vignettes/s3-vector.Rmd]: Never say never. Easy change though, when the time comes. https://github.com/tidymodels/probably/blob/ff58ca94305bbc792fc126ae270beac103149a94/R/vctrs-compat.R#L304

File: src/equal.c (hunk 5 above)
Comment (lionel-) [reply src/equal.c]: The proxy type of a tibble is `vctrs_type_dataframe`.

File: R/compare.R (hunk 4 above)
Comment (lionel-) [reply R/compare.R]: Yes I have added a test.
