### PR TITLE
Fix documentation of binding invariants

### LINKED ISSUE #286: Inconsistent behavior of `vec_rbind()` with 0-length input
I don't think these first two are quite right. They break this invariant:

```r
vec_size(vec_rbind(x, y)) == vec_size(x) + vec_size(y)
```

``` r
library(vctrs)

# not right?
vec_rbind(integer(), 1)
#> New names:
#>  -> ..1
#>   ..1
#> 1  NA
#> 2   1

# not right?
vec_rbind(integer(), data.frame(x = 1))
#>    x
#> 1 NA
#> 2  1

# this seems right
vec_rbind(integer(), integer())
#> data frame with 0 columns and 0 rows
```

Should the result just have 1 row, with `integer()` just being used to help determine the output container type?

### PR DESCRIPTION
**Pull request by lionel-**
Closes #286

### CODE REVIEW

File: R/bind.R [hunk 1]
```diff
@@ -6,9 +6,27 @@
 #' across all arguments.
 #'
 #' @section Invariants:
+#'
+#' All inputs are first converted to a data frame. How simple vectors
```
Comment (hadley) [inline R/bind.R]: The conversion for 1d vectors depends on the direction of binding:
