### PR TITLE
Fix `min()`, `max()` and `range()` where `na.rm = TRUE` and all values are `NA`

### LINKED ISSUE #1357: min and max throw an error if `na.rm = TRUE` and all values are `NA`
From tidyverse/haven#528 - `min()` and `max()` throw an error if all values are `NA` and `na.rm = TRUE`.
The base R versions return `Inf` or `-Inf` respectively.

They should possibly return `NA` instead of `Inf`/`-Inf`, see #1004.

``` r
min(NA_real_, na.rm = TRUE)
#> Warning in min(NA_real_, na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> [1] Inf
vctrs:::min.vctrs_vctr(NA_real_, na.rm = TRUE)
#> Error in idx[[1]]: subscript out of bounds

max(NA_real_, na.rm = TRUE)
#> Warning in max(NA_real_, na.rm = TRUE): no non-missing arguments to max;
#> returning -Inf
#> [1] -Inf
vctrs:::max.vctrs_vctr(NA_real_, na.rm = TRUE)
#> Error in idx[[1]]: subscript out of bounds
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

### PR DESCRIPTION
**Pull request by gorcha**
This PR fixes #1357. Where `na.rm = TRUE` and all values are `NA`, these functions now return `Inf`/`-Inf` or `NA` depending on the input type.

As noted in #1004, base R returns `Inf`/`-Inf` for numeric types, and `NA_character_` for character vectors, so it should do so in vctrs as well. I've followed almost the same rules here.

If `Inf`/`-Inf` can be successfully cast to the input type that will be the return value. Otherwise it will return `NA` cast to the appropriate type. This is kind of the same as base R in theory, but in vctrs doubles can't be cast to integer or logical, so these return `Inf` in base R but `NA` here.

This behaviour has been extended to empty vectors as well, so they no longer throw an error if `Inf` can't be cast to the input type.

I'm thinking that #1004 is right, and it should just be `NA` in all cases, but I've left `Inf` as the default where possible to match existing behaviour.

``` r
library(vctrs)

# Integer
min(integer())
#> Warning in min(integer()): no non-missing arguments to min; returning Inf
#> [1] Inf
min(new_vctr(integer()))
#> <vctrs_vctr[1]>
#> [1] NA

min(NA_integer_, na.rm = TRUE)
#> Warning in min(NA_integer_, na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> [1] Inf
min(new_vctr(NA_integer_), na.rm = TRUE)
#> <vctrs_vctr[1]>
#> [1] NA

# Double
min(numeric())
#> Warning in min(numeric()): no non-missing arguments to min; returning Inf
#> [1] Inf
min(new_vctr(numeric()))
#> <vctrs_vctr[1]>
#> [1] Inf

min(NA_real_, na.rm = TRUE)
#> Warning in min(NA_real_, na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> [1] Inf
min(new_vctr(NA_real_), na.rm = TRUE)
#> <vctrs_vctr[1]>
#> [1] Inf

# Character
min(character())
#> Warning in min(character()): no non-missing arguments, returning NA
#> [1] NA
min(new_vctr(character()))
#> <vctrs_vctr[1]>
#> [1] NA

min(NA_character_, na.rm = TRUE)
#> Warning in min(NA_character_, na.rm = TRUE): no non-missing arguments, returning
#> NA
#> [1] NA
min(new_vctr(NA_character_), na.rm = TRUE)
#> <vctrs_vctr[1]>
#> [1] NA

# Logical
min(logical())
#> Warning in min(logical()): no non-missing arguments to min; returning Inf
#> [1] Inf
min(new_vctr(logical()))
#> <vctrs_vctr[1]>
#> [1] NA

min(NA, na.rm = TRUE)
#> Warning in min(NA, na.rm = TRUE): no non-missing arguments to min; returning Inf
#> [1] Inf
min(new_vctr(NA), na.rm = TRUE)
#> <vctrs_vctr[1]>
#> [1] NA
```

<sup>Created on 2021-04-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

### CODE REVIEW

File: R/type-vctr.R [hunk 1]
```diff
@@ -475,17 +475,27 @@ quantile.vctrs_vctr <- function(x, ..., type = 1, na.rm = FALSE) {
...
-    return(vec_cast(Inf, x))
+    return(vec_cast_or_na(Inf, x))
   }
 
   # TODO: implement to do vec_arg_min()
   rank <- xtfrm(x)
 
   if (isTRUE(na.rm)) {
     idx <- which.min(rank)
+    if (vec_is_empty(idx)) {
```
Comment (lionel-) [inline R/type-vctr.R:496]: Are the empty idx cases covered by unit tests?

**Review by lionel- — COMMENTED** [review]
Seems reasonable until we figure out something better.

File: tests/testthat/test-type-vctr.R [hunk 2]
```diff
@@ -584,3 +584,26 @@ test_that("xtfrm() returns a bare vector", {
 test_that("xtfrm() works with character subclass", {
   expect_identical(xtfrm(new_vctr(chr())), int())
 })
+
+test_that("Summary generics behave identically to base if na.rm = TRUE and all values are NA (#1357)", {
+  expect_warning(
+    expect_identical(
+      min(new_vctr(NA_real_), na.rm = TRUE),
+      new_vctr(min(NA_real_, na.rm = TRUE))
```
Comment (hadley) [inline tests/testthat/test-type-vctr.R:592]: I think you should just inline `Inf` here, to make it easier to see what's going on (and then you don't need to suppress the warnings).

Comment (gorcha) [reply tests/testthat/test-type-vctr.R:592]: Good call, shall do. Thanks!

File: R/type-vctr.R (hunk 1 above)
Comment (gorcha) [reply R/type-vctr.R:496]: I don't think so, I'll add in some extra tests. Thanks!

**Comment by gorcha** [comment]
Thanks for the feedback, I've made that `vec_init()` change and expanded the tests to cover the NA and empty vector cases for double, integer, character and logical.

**Comment by lionel-** [comment]
Thanks for the nice PR @gorcha! You'll need to reset your remote master branch since I've pushed to it to resolve conflicts. To avoid this I recommend working from a branch that you can then delete after the patch is merged.
