### PR TITLE
Handle shape in combinations of native classes

### LINKED ISSUE #1290: Consider better error message for matrix times
```R
library(vctrs)

x <- rep(Sys.time(), 2)
dim(x) <- c(1, 2)

vec_c(x, x)
#> Error: `vec_cast.POSIXct.POSIXct()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

May just need a pointer to file an issue with reprex.

### LINKED ISSUE #1329: Row-binding date-arrays fails
``` r
x <- Sys.Date()
dim(x) <- 1
vctrs::vec_rbind(data.frame(x), data.frame(x))
#> Error: `vec_cast.Date.Date()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

From https://github.com/tidyverse/dplyr/issues/5779

### PR DESCRIPTION
**Pull request by lionel-**
Closes #1290.
Closes #1329.

### CODE REVIEW

File: tests/testthat/test-shape.R [hunk 1]
```diff
@@ -83,3 +83,23 @@ test_that("shape_broadcast_() applies recycling rules", {
...
+  dim(y) <- c(1, 3)
+
+  expect_snapshot(error = TRUE, vec_c(x, y))
+
+  d <- structure(Sys.Date(), dim = 1)
+  expect_equal(
+    vec_rbind(data.frame(d), data.frame(d)),
+    data.frame(d = structure(rep(Sys.Date(), 2), dim = 2))
+  )
+})
```
Comment (DavisVaughan) [inline tests/testthat/test-shape.R:105]: This isn't the best error message

```r
x <- factor(c("x", "y", "z"))
dim(x) <- c(3, 1)

y <- factor(c("x", "y", "z"))

vec_cast(x, y)
#> Error:
#> ! Can't convert `x` <factor<32af0>> to <factor<32af0>>.
#> Cannot decrease dimensions.
```

Maybe we could at least mention the dimensionality change? i.e.

```r
Can't decrease dimensionality from 2 to 1.
```

Comment (DavisVaughan) [inline tests/testthat/test-shape.R:105]: I think this would be a useful test because it:

- tests this with factors (and factor level unioning)
- tests broadcasting is working
- tests dimension names are broadcast

``` r
x <- factor(c("x", "y", "z"))
dim(x) <- c(3, 1)
dimnames(x) <- list(c("r1", "r2", "r3"), "c1")

y <- factor(c("w", "x", "y", "z"))
dim(y) <- c(2, 2)

vec_cast(x, y)
#>    c1 c1
#> r1 x  x 
#> r2 y  y 
#> r3 z  z 
#> Levels: w x y z
```

File: src/cast.c [hunk 2]
```diff
@@ -50,24 +50,27 @@ r_obj* vec_cast_opts(const struct cast_opts* opts) {
...
+    out = KEEP(vec_cast_dispatch_native(opts, x_type, to_type, &lossy));
   } else {
-    out = vec_cast_switch_native(opts, x_type, to_type, &lossy);
+    out = KEEP(vec_cast_switch_native(opts, x_type, to_type, &lossy));
   }
 
   if (lossy || out == r_null) {
+    // This broadcasts dimensions too
+    FREE(1);
     return vec_cast_dispatch_s3(opts);
```
Comment (DavisVaughan) [inline src/cast.c:65]: The idea here is that if you have a custom S3 type, and you expect that it can have dimensions, then you have to handle that yourself? Just checking

File: src/ptype2.c [hunk 3]
```diff
@@ -65,10 +65,15 @@ r_obj* vec_ptype2_opts_impl(const struct ptype2_opts* opts,
...
-    r_obj* out = vec_ptype2_dispatch_native(opts, x_type, y_type, left);
+    r_obj* out = KEEP(vec_ptype2_dispatch_native(opts, x_type, y_type, left));
+
     if (out != r_null) {
+      out = vec_shaped_ptype(out, x, y, x_arg, y_arg);
+      FREE(1);
       return out;
     }
+
+    FREE(1);
```
Comment (DavisVaughan) [inline src/ptype2.c:76]:
```suggestion
    r_obj* out = vec_ptype2_dispatch_native(opts, x_type, y_type, left);

    if (out != r_null) {
      KEEP(out);
      out = vec_shaped_ptype(out, x, y, x_arg, y_arg);
      FREE(1);
      return out;
    }
```

Are we allowed to only `KEEP()` `out` if we plan to actually use it?

Or is rchk going to yell at us for this?

File: tests/testthat/test-shape.R [hunk 4]
```diff
@@ -83,3 +83,23 @@ test_that("shape_broadcast_() applies recycling rules", {
     class = "vctrs_error_incompatible_type"
   )
 })
+
+test_that("can combine shaped native classes (#1290, #1329)", {
+  x <- Sys.time() + c(1, 1e6)
```
Comment (DavisVaughan) [inline tests/testthat/test-shape.R:88]: Would you mind using `new_datetime(c(1, 1e6))`? `Sys.time()` makes me slightly nervous

**Review by DavisVaughan — COMMENTED** [review]
I think I still would have preferred that we special case factor/Date/POSIXct to:
- Silently drop dimensions from arrays with dimensionality of 1
- Otherwise error with a message about how these classes can't be arrays and are unlikely to work properly

I guess that feels better to me because this seems like we are just propagating along the problem rather than trying to fix it like we do with integer storage `Date` vectors (and a few other things)

**Comment by DavisVaughan** [comment]
> special case factor/Date/POSIXct 

This does seem somewhat hard though, since we also have to think about fct<->chr and whatnot, so I guess I'm ok with this fix for now, and we can revisit if it causes any issues in the future

**Comment by lionel-** [comment]
> I guess that feels better to me because this seems like we are just propagating along the problem rather than trying to fix it

To me we're just fixing part of the problem, and hopefully dimensions may be more generally supported in the future. I see them as a core feature of R vectors, like names.

File: src/cast.c (hunk 2 above)
Comment (lionel-) [reply src/cast.c:65]: I think this is just falling back to the R implementations because we have been too lazy/busy to port the lossy cast paths to C.

File: src/ptype2.c (hunk 3 above)
Comment (lionel-) [reply src/ptype2.c:76]: rchk handles this case

File: tests/testthat/test-shape.R (hunk 1 above)
Comment (lionel-) [reply tests/testthat/test-shape.R:105]: Nice one

Comment (lionel-) [reply tests/testthat/test-shape.R:105]: This is now:

```
Error:
! Can't convert `x` <factor<32af0>[,1]> to <factor<32af0>>.
Can't decrease dimensionality from 2 to 1.
```

File: src/cast.c (hunk 2 above)
Comment (DavisVaughan) [reply src/cast.c:65]: Isn't this the standard S3 dispatch path too? i.e. if `out == r_null` we never hit a class we handle natively

Comment (lionel-) [reply src/cast.c:65]: ah maybe. But yes the intention was only to support dimensions on base classes.

It seems like it'd be too large a change to handle dimensions for S3 classes? I'm not sure how this would interact with classes like in rray.

Comment (DavisVaughan) [reply src/cast.c:65]: > It seems like it'd be too large a change to handle dimensions for S3 classes?

Yea my instinct is to not handle dimensions automatically for other S3 classes. Too magical and error prone I think
