### PR TITLE
Fix common type of subclasses of tibble

### LINKED ISSUE #481: vec_cbind returns wrong ptype
Before `vec_cbind` is implemented by C,
`vec_cbind(grouped_df, data.frame)` returned `tbl_df`.

However, from b7f4518, it is returning `data.frame` and causing `tdiyr:::nest.grouped_df` also returning `data.frame`.

This change is causing messy printing of nested data frame because of using `print.data.frame` instead of `print.tbl` (https://github.com/tidyverse/tidyr/issues/675).

## vctrs 0.2.0

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)
packageVersion("vctrs")
#> [1] '0.2.0'
d1 <- tibble(x=1:3)
d2 <- data.frame(y = 1:3)
vec_cbind(d1, d2) %>% class
#> [1] "tbl_df"     "tbl"        "data.frame"
vec_cbind(group_by(d1, x), d2) %>% class
#> [1] "data.frame"
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## vctrs 0.1.0

``` r
library(dplyr, warn.conflicts = FALSE)
library(vctrs)
packageVersion("vctrs")
#> [1] '0.1.0'
d1 <- tibble(x=1:3)
d2 <- data.frame(y = 1:3)
vec_cbind(d1, d2) %>% class
#> [1] "tbl_df"     "tbl"        "data.frame"
vec_cbind(group_by(d1, x), d2) %>% class
#> [1] "tbl_df"     "tbl"        "data.frame"
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by lionel-**
Closes #481.

### CODE REVIEW

File: R/type-tibble.R [hunk 1]
```diff
@@ -1,5 +1,10 @@
 # Coercion ----------------------------------------------------------------
 
+new_tibble <- function(df) {
```
Comment (hadley) [inline R/type-tibble.R]: I think calling this `new_tibble()` is potentially confusing because it's not really a constructor.

Comment (lionel-) [reply R/type-tibble.R]: Good point, it is now `df_as_tibble()`.
