### PR TITLE
Fix array restoration

### LINKED ISSUE #153: vec_restore.default() alters size and type
According to the docs:

> A `vec_restore()` method can assume that `x` has the correct type (although the length may be different) but all attributes have been lost and need to be restored.

This would lead me to believe that `x` can have a different size than `to`, which is the case when using `vec_restore()` with 1D vectors, but with matrices/arrays this isn't the case because all attributes of `to` are copied to `x`, including the `dim` (which embeds the size).

``` r
library(vctrs)

x <- matrix(1:5)

# dummy function to demonstrate losing attributes
# - type is the same (but attributes are needed)
# - size is now different
c_level_manip <- function(x) {
  vec_data(x)[1:2]
}

# I think this should work
vec_restore(c_level_manip(x), x)
#> Error in attributes(x) <- attributes(to): dims [product 5] do not match the length of object [2]

# special case the `dim` attribute
# pull size from x
# pull shape from to
vec_restore.default <- function(x, to) {
  restore_attr <- attributes(to)
  
  if ("dim" %in% names(restore_attr)) {
    restore_attr$dim <- c(vec_size(x), vctrs:::shape(to))
  }
  
  attributes(x) <- restore_attr
  x
}

vec_restore(vec_data(x)[1:2], x)
#>      [,1]
#> [1,]    1
#> [2,]    2
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Size is implicitly ignored with vectors:

``` r
library(vctrs)

ex <- factor(c("a", "a", "b"))

vec_restore(vec_data(ex[1]), ex)
#> [1] a
#> Levels: a b
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Update) This also would affect dimnames and general names. This is more difficult as the order or the rows would matter here when "restoring" names, but generally I think it isn't vctrs's job to restore names/dimnames so maybe they could just be removed.

``` r
library(vctrs)
x <- 1:5
names(x) <- letters[1:5]
vec_restore(vec_data(x[1:2]), x)
#> Error in attributes(x) <- attributes(to): 'names' attribute [5] must be the same length as the vector [2]
```

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

### PR DESCRIPTION
**Pull request by lionel-**
* `vec_restore()` is called after `vec_slice()` fallbacks to `[`.
* The default restore method preserves dimnames.
* Review assumptions that can be made by restoration methods in `?vec_restore`

Closes #153.

Does this look good @DavisVaughan?

### CODE REVIEW

File: R/cast.R [hunk 1]
```diff
@@ -46,14 +46,25 @@
...
-#' have been lost and need to be restored. In other words,
-#' `vec_restore(vec_data(x), x)` should yield `x`.
+#' A restore is a specialised type of cast, primarily used in
+#' conjunction with `NextMethod()` or a C-level function that works on
+#' the underlying data structure. A `vec_restore()` method can make
+#' the following assumptions about `x`:
+#'
+#' * It has the correct type.
+#' * It has the correct names.
+#' * It has the correct `dim` and `dimnames` attributes.
```
Comment (hadley) [inline R/cast.R]: How can this be true if " The length may be different" ?

File: R/slice.R [hunk 2]
```diff
@@ -48,16 +48,18 @@ vec_slice.default <- function(x, i) {
...
   } else if (d == 2) {
-    x[i, , drop = FALSE]
+    out <- x[i, , drop = FALSE]
   } else {
     miss_args <- rep(list(missing_arg()), d - 1)
-    eval_bare(expr(x[i, !!!miss_args, drop = FALSE]))
+    out <- eval_bare(expr(x[i, !!!miss_args, drop = FALSE]))
   }
+
+  vec_restore(out, x)
```
Comment (hadley) [inline R/slice.R]: It seems weird to restore if we've called `[` on something that's an S3 object?

File: tests/testthat/test-cast.R [hunk 3]
```diff
@@ -195,3 +195,15 @@ test_that("vec_restore() passes `i` argument to methods", {
...
+test_that("dimensions are preserved by default restore method", {
+  x <- foobar(1:4)
+  dim(x) <- c(2, 2)
+  dimnames(x) <- list(a = c("foo", "bar"), b = c("quux", "hunoz"))
+
+  exp <- foobar(c(1L, 3L))
+  dim(exp) <- c(1, 2)
+  dimnames(exp) <- list(a = "foo", b = c("quux", "hunoz"))
+
+  expect_identical(vec_slice(x, 1), exp)
```
Comment (hadley) [inline tests/testthat/test-cast.R]: Shouldn't this call `vec_restore()` since we're testing it?

File: R/cast.R (hunk 1 above)
Comment (lionel-) [reply R/cast.R]: Because we restore dim and dimnames so that they reflect the new size.

File: tests/testthat/test-cast.R (hunk 3 above)
Comment (lionel-) [reply tests/testthat/test-cast.R]: `vec_slice()` calls `vec_restore()`.

File: R/slice.R (hunk 2 above)
Comment (lionel-) [reply R/slice.R]: Good point, I'll change to only call it on non-OO objects with dims.

Comment (lionel-) [reply R/slice.R]: Actually, calling `vec_restore()` here is congruent with how `vec_slice()` automatically restores the class and attributes. The `[.foo` methods should call `vec_slice()` but not `vec_restore()`. Then the call path for a foo object with dims is `[` -> `vec_slice()` -> `unclass()` -> `[` -> `vec_restore()`.

I have simplified `vec_slice_fallback()` (which is only called with shaped objects and should be removed in the future when we support those natively) and added a missing `unclass()`.

Still need to figure out what to do when additional arguments are passed to `[` methods. Currently higher dimensions are ignored.

Comment (lionel-) [reply R/slice.R]: I guess the current situation is confusing because of contradictory use cases:

- Using `vec_slice()` from our `[` methods for consistency of behaviour.
- Calling `[` from `vec_slice()` to handle shaped objects because we don't have native slicing for these in vctrs.
- Calling `[` from `vec_slice()` to handle S3 objects as a fallback.

With `[.vctrs_vctr` we'd like to restore after slicing shaped objects with `[`. With foreign classes we don't want to restore.

This will be less confusing once we slice shape natively. I'll try to find an interim solution.

Comment (hadley) [reply R/slice.R]: You can leave it for now and tackle in a future PR if you want.

**Comment by DavisVaughan** [comment]
@lionel- this PR allowed me to remove all of my hacks in rray! I'm happy with it.
