### PR TITLE
Fix error message when combining outer name with single inner name

### LINKED ISSUE #522: Better error message for vec_c() outer name failure
In this case the problem is that there are inner names and outer names, not that the vector has length > 1

``` r
vctrs::vec_c(x = c(xx = 1))
#> Error: Can't merge the outer name `x` with a vector of length > 1.
#> Please supply a `.name_spec` specification.
```

<sup>Created on 2019-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by lionel-**
Closes #522

### CODE REVIEW

File: src/names.c [hunk 1]
```diff
@@ -589,11 +589,18 @@ r_obj* apply_name_spec(r_obj* name_spec, r_obj* outer, r_obj* inner, r_ssize n)
...
     break;
-  case R_TYPE_null:
-    r_abort("Can't merge the outer name `%s` with a vector of length > 1.\n"
+  case R_TYPE_null: {
+    const char* reason;
+    if (n > 1) {
+      reason = "a vector of length > 1";
+    } else {
+      reason = "a named vector";
+    }
```
Comment (DavisVaughan) [inline src/names.c:598]: Here I'm just explicitly documenting that the grid of possibilities is `outer` + one of:
- Length 1 unnamed vector (allowed)
- Length 1 named vector (`"a named vector"` error)
- Length >1 unnamed vector (`"a vector of length >1"` error)
- Length >1 named vector (`"a vector of length >1"` error)

And the following length 0 cases don't ever go through this error path (may or may not be worth a test, up to you)

``` r
# Length 0 unnamed vector
vctrs::vec_c(x = integer())
#> named integer(0)

# Length 0 named vector
vctrs::vec_c(x = rlang::set_names(integer(), character()))
#> named integer(0)
```

**Review by DavisVaughan — APPROVED** [review]

File: src/names.c (hunk 1 above)
Comment (lionel-) [reply src/names.c:598]: The first test case might have been missing, I've added it in case.
