### PR TITLE
Revert to a simpler ownership model - but always duplicate ALTREP

### LINKED ISSUE #1122: vec_rbind() performance regression on R 4.0 with df-cols
Performance regression when rbinding lots of data frames that have df-cols. I'm sure this has to do with making extra copies, but I'm not sure where yet. I'll take a look.

This is with dev vctrs.

R 3.6

```r
library(vctrs)

df_col <- new_data_frame(list(x = 1:2))
df <- new_data_frame(list(y = df_col))

x <- rep_len(list(df), 10000)
y <- rep_len(list(df_col), 10000)

lst_rbind <- function(x) {
  vec_rbind(!!!x)
}

bench::mark(lst_rbind(x))
#> # A tibble: 1 x 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 lst_rbind(x)   37.5ms   37.9ms      26.2     277KB     52.4

bench::mark(lst_rbind(y))
#> # A tibble: 1 x 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 lst_rbind(y)   16.5ms   18.2ms      55.1     274KB     16.5
```

R 4.0

```r
library(vctrs)

df_col <- new_data_frame(list(x = 1:2))
df <- new_data_frame(list(y = df_col))

x <- rep_len(list(df), 10000)
y <- rep_len(list(df_col), 10000)

lst_rbind <- function(x) {
  vec_rbind(!!!x)
}

bench::mark(lst_rbind(x))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 lst_rbind(x)    316ms    352ms      2.84     764MB     48.2

bench::mark(lst_rbind(y))
#> # A tibble: 1 x 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 lst_rbind(y)   15.8ms   17.6ms      55.6     274KB     23.4
```

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes tidyverse/dplyr#5327
Closes #1124
Closes #1122 

Reverts back to a slightly simpler ownership model of `VCTRS_OWNED_true` and `VCTRS_OWNED_false`.

When we own the object, we only ever attempt to duplicate it if it is ALTREP. If `vec_init()` ever creates ALTREP objects in the future (https://github.com/r-lib/vctrs/pull/837), this will be required. When doing assignment, we have to duplicate ALTREP objects before dereferencing even if we own them, because we need access to the actual data that it is representing, not the ALTREP object's internals.

When we don't own the object, we use `r_clone_referenced()` to determine if we need to duplicate or not.

This fixed the repeated duplication that was occurring in `df_assign()`'s calls to `vec_proxy_assign_opts()`, but I then discovered that we still had repeated duplication in `vec_restore()`. To fix that, I had to borrow from the ideas in #1124 and pass through `owned` to `vec_restore()` as well. This allows us to avoid attempting duplication here as well.

With both of those in place, tidyverse/dplyr#5327 is fixed:

```r
library(dplyr)

date_frame <- tibble(date = rep(lubridate::date("2020-01-01"), 100))
date_frames_to_bind <- rep(list(date_frame), 10000)
bench::mark(bind_rows(date_frames_to_bind))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression                          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 bind_rows(date_frames_to_bind)    133ms    142ms      6.87    8.39MB     25.8
```

---

It is worth noting that @lionel- and I both think that eventually we should probably have recursive proxy and restore functions (https://github.com/r-lib/vctrs/issues/1107). This would allow `df_assign()` to not have to proxy and restore the output columns repeatedly, which is where many of these duplication issues arise. That would also allow us to remove the `owned` argument from `vec_restore()` again, which I am currently viewing as a temporary fix.

---

This also closes #1124, because it fixes the original problem there where columns of df-cols were being duplicated.

### CODE REVIEW

File: src/owned.h [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+}
+
+// Wrapper around `r_clone_referenced()` that only attempts to clone if
+// we indicate that we don't own `x`, or if we do own `x` but it is ALTREP.
+// If `x` is ALTREP, we must clone it before dereferencing, otherwise we get
+// a pointer into the ALTREP internals rather than into the object it
+// truly represents.
+static inline SEXP vec_clone_referenced(SEXP x, const enum vctrs_owned owned) {
+  if (owned == VCTRS_OWNED_false || ALTREP(x)) {
+    return r_clone_referenced(x);
```
Comment (lionel-) [inline src/owned.h:26]: ALTREP objects should be copied unconditionally right? Even if they are maxed out in references, I think it would be clearer to copy unconditionally.

File: tests/testthat/helper-performance.R [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+
+  skip("Not testing performance")
+}
+
+expect_time_lt <- function(expr, expect) {
+  time <- time_expr({{ expr }})
+  expect_lt(time, expect)
+}
+
+time_expr <- function(expr) {
```
Comment (lionel-) [inline tests/testthat/helper-performance.R:17]: `time_of()`?
